server:
  port: 8000

spring:
  profiles:
    active: dev
  data:
    redis:
      repositories:
        enabled: false

  redis:
    # 数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 最大连接数
        max-active: 100
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        # 最大空闲
        max-idle: 500
        # 最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000

# MyBatis配置
mybatis:
  # Mapper映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 包下所有类的别名，配置别名为了在对象映射文件中接收参数类型和返回参数类型时省略包路径
  type-aliases-package: com.daniellin07.bookshop.domain

# 七牛云
qiniu:
  # 文件大小 /M
  max-size: 5

# 验证码有效时间/分钟
code:
  expiration: 5